### PR TITLE
add code to generate a plot to show the scale-free fit for different …

### PR DESCRIPTION
**Pull request by plane83**
Fei wrote some R code to generate a figure to show the scale-free fit for different powers used in WGCNA.

### CODE REVIEW

**Comment by sjyoo** [comment]
Fei, don't we need to use upto max power at least not limited to 20?

I'll merge PR anyway... for the time being...

**Comment by plane83** [comment]
It is 20 right now.
https://github.com/kbase/coexpression/blob/develop/scripts/coex_cluster2.R

powers = c(c(1:20),seq(from=1, to=20,by=2))

On Tue, Feb 2, 2016 at 1:04 PM, sjyoo notifications@github.com wrote:

> Fei, don't we need to use upto max power at least not limited to 20?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kbase/coexpression/pull/17#issuecomment-178761344.

## 

Fei He

**Comment by sjyoo** [comment]
What if if the max power is beyond 20?

Thanks,
-SJ

**Comment by plane83** [comment]
Use 20 is just to follow the default setup in WGCNA.
Showing the scale-free fitting does not mean the network has to be
scale-free.

On Tue, Feb 2, 2016 at 1:09 PM, sjyoo notifications@github.com wrote:

> What if if the max power is beyond 20?
> 
> Thanks,
> -SJ
> 
> On Tue, Feb 2, 2016 at 2:07 PM, plane83 notifications@github.com wrote:
> 
> > It is 20 right now.
> > 
> > https://github.com/kbase/coexpression/blob/develop/scripts/coex_cluster2.R
> > 
> > powers = c(c(1:20),seq(from=1, to=20,by=2))
> > 
> > On Tue, Feb 2, 2016 at 1:04 PM, sjyoo notifications@github.com wrote:
> > 
> > > Fei, don't we need to use upto max power at least not limited to 20?
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/kbase/coexpression/pull/17#issuecomment-178761344
> > > .
> > 
> > ## 
> > 
> > Fei He
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/kbase/coexpression/pull/17#issuecomment-178763035.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kbase/coexpression/pull/17#issuecomment-178763840.

## 

Fei He

**Pull request merged**
